spring:
  profiles:
    active: produce

---

spring:
  config:
    activate:
      on-profile: develop

lesson: SpringBoot

server:
  port: 8082

enterprise:
  name: zsh
  age: 18
  tel: 83225361
  subject:
    - Java
    - Python
    - C++

---

spring:
  config:
    activate:
      on-profile: produce

server:
  port: 8083

---

spring:
  config:
    activate:
      on-profile: test

server:
  port: 8084
